# Generated by Django 2.2.14 on 2020-07-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poet',
            options={'ordering': ('first_name',), 'verbose_name': 'Поэт(эсса)'},
        ),
    ]
