# Generated by Django 2.2.14 on 2020-07-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20200731_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ('title',), 'verbose_name': 'Стихотворение'},
        ),
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.Poet', verbose_name='Автор(ша)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год(ы)'),
        ),
    ]
